from app.shared.schema import CamelModel


class GuestSessionRequest(CamelModel):
    """The widget's only way to identify which tenant it belongs to before
    it has any credential — the tenant's public slug, embedded in the
    install snippet generated by Widget Studio (FR-2.4). Never a secret:
    anyone viewing the partner site's page source can already see it, the
    same way they can see which site they're on."""

    tenant_slug: str


class GuestSessionResponse(CamelModel):
    access_token: str
    refresh_token: str
    customer_id: str
    tenant_id: str


class RefreshRequest(CamelModel):
    refresh_token: str
